### ISSUE TITLE
Training cost

### ISSUE THREAD

**Issue by yuhuUSTC** [mit-han-lab/hart#1]
Thanks for the great work!
I'm interested in the training cost of this work. 
VAR is reported to cost 256 A100 GPUs for 4 days for 350 epochs for VAR-d30 on ImageNet 512x512. 
This work seems to have similar training cost as VAR. Then how is the training cost for 1024x1024.

**Comment by kentang-mit** [comment]
Hi @yuhuUSTC,

Thanks for the kind words. The training cost is roughly 64 A100 GPUs for ~10 days (this includes all 3 training stages at 256px, 512px and 1024px).

Best,
Haotian

**Comment by yuhuUSTC** [comment]
Thanks~
